# Generated by Django 4.2.3 on 2023-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="images/")),
                ("title", models.CharField(max_length=30)),
                ("mavzu", models.CharField(max_length=150)),
            ],
        ),
    ]
